name: phase1tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  phase1tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Setup Repo
        run: ./run install

      - name: Run Tests
        run: ./run test